#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v27
# autospec commit: 6aaa12f
#
Name     : tevent
Version  : 0.16.2
Release  : 49
URL      : https://www.samba.org/ftp/tevent/tevent-0.16.2.tar.gz
Source0  : https://www.samba.org/ftp/tevent/tevent-0.16.2.tar.gz
Summary  : An event system library
Group    : Development/Tools
License  : LGPL-3.0 LGPL-3.0+
Requires: tevent-lib = %{version}-%{release}
Requires: tevent-license = %{version}-%{release}
Requires: tevent-python = %{version}-%{release}
Requires: tevent-python3 = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : python3-dev
BuildRequires : talloc-dev
BuildRequires : talloc-extras
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-add-mock-disable-static-option.patch

%description
This subsystem ensures that we can always use a certain core set of
functions and types, that are either provided by the OS or by replacement
functions / definitions in this subsystem. The aim is to try to stick
to POSIX functions in here as much as possible. Convenience functions
that are available on no platform at all belong in other subsystems
(such as LIBUTIL).

%package dev
Summary: dev components for the tevent package.
Group: Development
Requires: tevent-lib = %{version}-%{release}
Provides: tevent-devel = %{version}-%{release}
Requires: tevent = %{version}-%{release}

%description dev
dev components for the tevent package.


%package lib
Summary: lib components for the tevent package.
Group: Libraries
Requires: tevent-license = %{version}-%{release}

%description lib
lib components for the tevent package.


%package license
Summary: license components for the tevent package.
Group: Default

%description license
license components for the tevent package.


%package python
Summary: python components for the tevent package.
Group: Default
Requires: tevent-python3 = %{version}-%{release}

%description python
python components for the tevent package.


%package python3
Summary: python3 components for the tevent package.
Group: Default
Requires: python3-core

%description python3
python3 components for the tevent package.


%prep
%setup -q -n tevent-0.16.2
cd %{_builddir}/tevent-0.16.2
%patch -P 1 -p1
pushd ..
cp -a tevent-0.16.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749156158
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-rpath \
--disable-rpath-install
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-rpath \
--disable-rpath-install
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1749156158
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tevent
cp %{_builddir}/tevent-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/tevent/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/tevent-%{version}/lib/talloc/LICENSE %{buildroot}/usr/share/package-licenses/tevent/f45ee1c765646813b442ca58de72e20a64a7ddba || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/lib/python3.*/site-packages/talloc.cpython-*-x86_64-linux-gnu.so
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/tevent.h
/usr/lib64/libtevent.so
/usr/lib64/pkgconfig/tevent.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libtevent.so.0.16.2
/V3/usr/lib64/tevent/libcmocka-tevent.so
/usr/lib64/libtevent.so.0
/usr/lib64/libtevent.so.0.16.2
/usr/lib64/tevent/libcmocka-tevent.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tevent/f45ee1c765646813b442ca58de72e20a64a7ddba

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
